### ISSUE TITLE
質問

### ISSUE THREAD

**Issue by c0a2109372** [MikamiSyota/ProjExD#4]
https://github.com/MikamiSyota/ProjExD/blob/0644573ab6b463ae6945076de407f684c3a6578e/ex02/calc.py#L58
⑧などの機能がよくわからないです

**Comment by MikamiSyota** [comment]
数値が○で囲われているのは10進数を○で囲われてる数値の進数に変更するものです。button_click関数の中身を見ていただければ、bin(),oct(),hex()関数が使われているのでその点でなんとかしていただけると思います。

**Comment by MikamiSyota** [comment]
実際⑩は実装しきれていないので削除させていただきます。
ご指摘ありがとうございます。
