### ISSUE TITLE
こうかとん増員依頼

### ISSUE THREAD

**Issue by c0a21021** [MikamiSyota/ProjExD#8]
https://github.com/MikamiSyota/ProjExD/blob/0d9a53fb31a504a7a72cc4d6da8e172fc582a48f/ex03/maze.py#L31
もっとこうかとん増やしてみてほしいです

**Comment by MikamiSyota** [comment]
一度増やしたのですが、多すぎてやかましかったので削除してしまいました。なので、大変ありがたいご意見ですが増員はご遠慮いたします。
